# Generated by Django 2.2.3 on 2019-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(choices=[(1, '남성'), (2, '여성')], default=1)),
                ('num_people', models.IntegerField(choices=[(1, '2:2'), (2, '3:3'), (3, '4:4'), (4, '5:5'), (5, '기타')], default=1)),
                ('campus', models.IntegerField(choices=[(1, '명륜'), (2, '율전'), (3, '기타')], default=1)),
                ('title', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
            ],
        ),
    ]
