# Generated by Django 2.2.3 on 2019-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=50)),
                ('write_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
